//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DataPUE.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class COLONIAS
    {
        public decimal COLONIA_ID { get; set; }
        public Nullable<decimal> CLAVE { get; set; }
        public string COLONIA { get; set; }
        public Nullable<decimal> CP { get; set; }
        public string CLAVEM { get; set; }
    }
}
